server:
  port: 8189
  servlet:
    context-path: /hr
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/hrdb
    username: postgres
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml


    url: jdbc:postgresql://localhost:5432/hrdb
    user: postgres
    password: root1
  main:
    allow-circular-references: true