server:
  port: 8189
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/hrdb
    username: postgres
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  main:
    allow-circular-references: true