server:
  port: 8180
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrdb
    username: postgres
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
      

    url: jdbc:postgresql://localhost:5432/hrdb
    user: postgres
    password: root1